server:
  port: 8082

spring:
  profiles:
    active: dev #多文件支持，开发用dev，对应application-dev.yml中配置，正式的时候配置成prod，对应application-prod.yml中配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #处理返回给前台的日期格式
#配置mymybatis相关信息
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zzq.springbootdemo.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

#配置quartz
org:
  quartz:
    scheduler:
      instanceName: jlDe1919Scheduler #调度器实例名称
      instanceId: AUTO #调度器实例编号自动生成
    jobStore:
      class: org.quartz.simpl.RAMJobStore
      useProperties: false #配置是否使用
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool #线程池实现类
      threadCount: 10 #执行最大并发线程数量
      threadPriority: 5 #线程优先级
      threadsInheritContextClassLoaderOfInitializingThread: true #配置是否启动自动加载数据库内的定时任务，默认true

debug: false