server:
  port: 8082

spring:
  profiles:
    active: dev #多文件支持，开发用dev，对应application-dev.yml中配置，正式的时候配置成prod，对应application-prod.yml中配置

#配置mymybatis相关信息
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zzq.springbootdemo.model

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

#配置quartz
quartz:
  properties:
    org:
      quartz:
        scheduler:
          instanceName: clusteredScheduler #调度器实例名称
          instanceId: AUTO #调度器实例编号自动生成
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化方式,配置JobStoreCMT是依赖于容器来进行事务的管理，而JobStoreTX是自己管理事务
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #持久化方式配置数据驱动，MySQL数据库
          tablePrefix: QRTZ_ #quartz相关数据表前缀名
          isClustered: false #开启分布式部署
          clusterCheckinInterval: 10000 #分布式节点有效性检查时间间隔，单位：毫秒
          useProperties: false #配置是否使用
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool #线程池实现类
          threadCount: 10 #执行最大并发线程数量
          threadPriority: 5 #线程优先级
          threadsInheritContextClassLoaderOfInitializingThread: true #配置是否启动自动加载数据库内的定时任务，默认true
    job-store-type: jdbc

debug: false